language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

arch: 
  - amd64
  - arm64

install: true

jobs:
  include:
    - stage: test
      go: 1.12.x
      script:
        - ./scripts/test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - ${HOME}/.cache/go-build
          - ${HOME}/gopath/pkg/mod
    - stage: build
      go: 1.12.x
      arch: amd64
      script:
        - ./scripts/build.sh
      cache:
        directories:
          - ${HOME}/.cache/go-build
          - ${HOME}/gopath/pkg/mod
    - stage: buildarm
      go: 1.12.x
      arch: arm64
      script:
        - ./scripts/buildarm.sh
      cache:
        directories:
          - ${HOME}/.cache/go-build
          - ${HOME}/gopath/pkg/mod      